/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAppointmentsRouteImport } from './routes/app.appointments'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppClientsIndexRouteImport } from './routes/app.clients.index'
import { Route as AppClientsClientIdRouteImport } from './routes/app.clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/clients': typeof AppClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/appointments': typeof AppAppointmentsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/assistant'
    | '/app/payments'
    | '/app/settings'
    | '/app/'
    | '/app/clients/$clientId'
    | '/app/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/assistant'
    | '/app/payments'
    | '/app/settings'
    | '/app'
    | '/app/clients/$clientId'
    | '/app/clients'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/assistant'
    | '/app/payments'
    | '/app/settings'
    | '/app/'
    | '/app/clients/$clientId'
    | '/app/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appointments': {
      id: '/app/appointments'
      path: '/appointments'
      fullPath: '/app/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
